### PR TITLE
Prepare for P3

### PR DESCRIPTION
**Pull request by samiheikki**
Prepare for Polymer3

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/license-checker/50)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[a discussion](https://beta.reviewable.io/reviews/vaadin/license-checker/50#-L9A4RJ2Effm41On_XBv:-L9A4RJ2Effm41On_XBw:b-fxxgyz) (no related file):*
package.json needs to be updated

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/license-checker/50)*

**Comment by samiheikki** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/license-checker/50#-L9A4RJ2Effm41On_XBv:-L9Agntu72MeihF39Lt2:bb6un1j) (no related file):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

package.json needs to be updated
</blockquote></details>

Done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/license-checker/50)*

**Comment by tomivirkki** [comment]
*[vaadin-license-checker.html, line 221 at r2](https://beta.reviewable.io/reviews/vaadin/license-checker/50#-L9FjY3Z3H2zfmxrt0ZG:-L9FjY3Z3H2zfmxrt0ZH:b-5kdb47) ([raw file](https://github.com/vaadin/license-checker/blob/b44eaf999d4eb7b218ad34faa99243e3fd578fa1/vaadin-license-checker.html#L221)):*
> ```HTML
>   window.Vaadin = window.Vaadin || {};
>   window.Vaadin.LicenseChecker = window.Vaadin.LicenseChecker || new LicenseChecker();
>   window.Vaadin.LicenseCheckerClass = window.Vaadin.LicenseCheckerClass || LicenseChecker;
> ```

These seem to convert into `window.Vaadin.LicenseCheckerClass = ` instead of `export const LicenseChecker` (this may require adding `@namespace`). Is this intentional?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/license-checker/50)*

**Comment by samiheikki** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-license-checker.html, line 221 at r2](https://beta.reviewable.io/reviews/vaadin/license-checker/50#-L9FjY3Z3H2zfmxrt0ZG:-L9GQXLh7KLKXQekR1Fj:b-rsoscq) ([raw file](https://github.com/vaadin/license-checker/blob/b44eaf999d4eb7b218ad34faa99243e3fd578fa1/vaadin-license-checker.html#L221)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

These seem to convert into `window.Vaadin.LicenseCheckerClass = ` instead of `export const LicenseChecker` (this may require adding `@namespace`). Is this intentional?
</blockquote></details>

Added namespace

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/license-checker/50)*

**Comment by tomivirkki** [comment]
*[vaadin-license-checker.html, line 221 at r2](https://beta.reviewable.io/reviews/vaadin/license-checker/50#-L9FjY3Z3H2zfmxrt0ZG:-L9P6Ed48izOHbIyO8WX:b-o48aoo) ([raw file](https://github.com/vaadin/license-checker/blob/b44eaf999d4eb7b218ad34faa99243e3fd578fa1/vaadin-license-checker.html#L221)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Added namespace
</blockquote></details>

Now they convert as exports but none of the tests pass on Polymer 3

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/license-checker/50)*

**Comment by samiheikki** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-license-checker.html, line 221 at r2](https://beta.reviewable.io/reviews/vaadin/license-checker/50#-L9FjY3Z3H2zfmxrt0ZG:-L9ZtJwQ7JSjcBYvweaz:b-j9p8oi) ([raw file](https://github.com/vaadin/license-checker/blob/b44eaf999d4eb7b218ad34faa99243e3fd578fa1/vaadin-license-checker.html#L221)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Now they convert as exports but none of the tests pass on Polymer 3
</blockquote></details>

I actually reverted back to `window.Vaadin.LicenseChecker`. I think they should be added to `window`. If you for example look at how license-checker is used in charts: https://github.com/vaadin/vaadin-charts/blob/master/vaadin-chart.html#L1136. I came to this conclusion looking at the `

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/license-checker/50)*

**Comment by samiheikki** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-license-checker.html, line 221 at r2](https://beta.reviewable.io/reviews/vaadin/license-checker/50#-L9FjY3Z3H2zfmxrt0ZG:-L9Zuxo_BKqREmwNW7pW:b6oxsh5) ([raw file](https://github.com/vaadin/license-checker/blob/b44eaf999d4eb7b218ad34faa99243e3fd578fa1/vaadin-license-checker.html#L221)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

I actually reverted back to `window.Vaadin.LicenseChecker`. I think they should be added to `window`. If you for example look at how license-checker is used in charts: https://github.com/vaadin/vaadin-charts/blob/master/vaadin-chart.html#L1136. I came to this conclusion looking at the `
</blockquote></details>

At the `

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/license-checker/50)*

**Comment by samiheikki** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-license-checker.html, line 221 at r2](https://beta.reviewable.io/reviews/vaadin/license-checker/50#-L9FjY3Z3H2zfmxrt0ZG:-L9ZvAHH58bJUhGJ2-Sw:b-ss911v) ([raw file](https://github.com/vaadin/license-checker/blob/b44eaf999d4eb7b218ad34faa99243e3fd578fa1/vaadin-license-checker.html#L221)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

At the `
</blockquote></details>

Lol why does it cut my message. ... Looking at the vaadin-usage-statistics#p3-preview branch. But not 100% sure.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/license-checker/50)*

**Comment by manolo** [comment]
Coping this PR and opening a new one in `vaadin/license-checker` otherwise it does not pass travis 

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/license-checker/50#-:-L9j-fwP11cIUC2275K8:b-v8liuk)*

**Comment by manolo** [comment]
Closing this, pls continue discussion in #51

**Pull request closed without merging**
