### PR TITLE
Add js framework identifier

### PR DESCRIPTION
**Pull request by samiheikki**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/license-checker/7)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[a discussion](https://reviewable.io:443/reviews/vaadin/license-checker/7#-KGlM0ORWpcLCPRV3RAy:-KGlM0OSCTAJ4_JS4buw:-826222340) (no related file):_
Looks like there's an issue and the header is not actually included in the request.
Tested using network tab in dev tools.
Might be related to the fact that [headers property](https://elements.polymer-project.org/elements/iron-ajax#property-headers) is Object and we are "stringifying" it.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/license-checker/7)_

**Comment by alvarezguille** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[a discussion](https://reviewable.io:443/reviews/vaadin/license-checker/7#-KGlM0ORWpcLCPRV3RAy:-KGlOZsbn0yN_Vh8HY52:-1134200133) (no related file):_
Indeed removing `JSON.stringify` solves it

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/license-checker/7)_

**Comment by alvarezguille** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_[vaadin-framework-identifier.html, line 85 [r2]](https://reviewable.io:443/reviews/vaadin/license-checker/7#-KGp_PNcb-6lGSxt9rlE:-KGp_PNcb-6lGSxt9rlF:-196562153) ([raw file](https://github.com/vaadin/license-checker/blob/5838cdfe264a47652c6e37d816ed8aeb1917d47e/vaadin-framework-identifier.html#L85)):_
can we add Polymer.version here too?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/license-checker/7)_

**Comment by samiheikki** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[vaadin-framework-identifier.html, line 85 [r2]](https://reviewable.io:443/reviews/vaadin/license-checker/7#-KGp_PNcb-6lGSxt9rlE:-KGpi7Upfe1Ekb7oexGH:-499146009) ([raw file](https://github.com/vaadin/license-checker/blob/5838cdfe264a47652c6e37d816ed8aeb1917d47e/vaadin-framework-identifier.html#L85)):_
Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/license-checker/7)_

**Comment by alvarezguille** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/license-checker/7#-:-KGpjntNe7Sv3_VeIfUB:1417088721)_

**Pull request merged**
