### PR TITLE
P3 preview

### PR DESCRIPTION
**Pull request by tomivirkki**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/license-checker/53)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @tomivirkki)

---

*[vaadin-license-checker.html, line 162 at r4](https://reviewable.io/reviews/vaadin/license-checker/53#-LFRzJov0XQaSsZim1yY:-LFRzJov0XQaSsZim1yZ:b-dozbvu) ([raw file](https://github.com/vaadin/license-checker/blob/f879efd0145fa7274a0e8bb6294bb4b0233a679a/vaadin-license-checker.html#L162)):*
> ```HTML
> 
>     static get version() {
>       return '2.0.1-pre.1';
> ```

should be without pre

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/license-checker/53)*

**Comment by tomivirkki** [comment]
Review status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @manolo)

---

*[vaadin-license-checker.html, line 162 at r4](https://reviewable.io/reviews/vaadin/license-checker/53#-LFRzJov0XQaSsZim1yY:-LFRzzx-8EumS_Y1XKHN:b-896fix) ([raw file](https://github.com/vaadin/license-checker/blob/f879efd0145fa7274a0e8bb6294bb4b0233a679a/vaadin-license-checker.html#L162)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

should be without pre
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/license-checker/53)*

**Comment by manolo** [comment]
Review status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @tomivirkki)

---

*[bower.json, line 21 at r5](https://reviewable.io/reviews/vaadin/license-checker/53#-LFS-8cp82tS-1zdspT8:-LFS-8cp82tS-1zdspT9:bwdmmj8) ([raw file](https://github.com/vaadin/license-checker/blob/f98f629d2012ccdb078bcc9dc74bf8ba5517b0a5/bower.json#L21)):*
> ```JSON
>     "web-component-tester": "^6.0.0",
>     "iron-test-helpers": "PolymerElements/iron-test-helpers#^2.0.0",
>     "vaadin-development-mode-detector": "vaadin/vaadin-development-mode-detector#^1.1.0-alpha2"
> ```

should be ^1.1.0 ? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/license-checker/53)*

**Comment by tomivirkki** [comment]
Review status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @manolo)

---

*[bower.json, line 21 at r5](https://reviewable.io/reviews/vaadin/license-checker/53#-LFS-8cp82tS-1zdspT8:-LFS-RnY388GpKUyJf_3:b-896fix) ([raw file](https://github.com/vaadin/license-checker/blob/f98f629d2012ccdb078bcc9dc74bf8ba5517b0a5/bower.json#L21)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

should be ^1.1.0 ? 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/license-checker/53)*

**Comment by manolo** [comment]
:lgtm: 

---

Reviewed 7 of 11 files at r1, 1 of 3 files at r2, 2 of 2 files at r4, 1 of 1 files at r5.
Review status: 10 of 11 files reviewed, all discussions resolved (waiting on @manolo)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/license-checker/53#-:-LFS0Coq3uGy6SkKofwt:bg7igkv)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r6.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/license-checker/53)*

**Pull request merged**
